CREATE TABLE IF NOT EXISTS USER_ALBUM ( ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT, ACTIVE INTEGER );
ALTER TABLE USER_PHOTO ADD USER_ALBUM INTEGER;
ALTER TABLE UNSPLASH_CATEGORY ADD ACTIVE INTEGER;